services:
  mongo:
    image: mongo:latest
    container_name: my-mongo-instance
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  parse-server:
    image: parseplatform/parse-server:latest
    container_name: my-parse-server
    ports:
      - "1337:1337"
    volumes:
      - config-vol:/parse-server/config
      - D:/FlutterProject/nweekn/parse-server/cloud:/parse-server/cloud
    environment:
      - PARSE_SERVER_APPLICATION_ID=nweeknid
      - PARSE_SERVER_MASTER_KEY=mnweeknkey
      - PARSE_SERVER_DATABASE_URI=mongodb://mongo/nweekn
      - PARSE_SERVER_CLOUD=/parse-server/cloud/main.js
      - PARSE_SERVER_MASTER_KEY_IPS=172.18.0.0/16
    depends_on:
      - mongo

  parse-dashboard:
    image: parseplatform/parse-dashboard:latest
    container_name: parse-dashboard
    user: root
    ports:
      - "4040:4040"
    volumes:
    - ./parse-dashboard-config.json:/Parse-Dashboard/parse-dashboard-config.json
    command: ["--config", "/Parse-Dashboard/parse-dashboard-config.json", "--allowInsecureHTTP", "--dev"]
#    command: [
#      "--appId", "APPLICATION_ID",
#      "--masterKey", "MASTER_KEY",
#      "--serverURL", "http://my-parse-server:1337/parse",
#      "--appName", "optionalName",
#      "--allowInsecureHTTP",
#      "--dev",
#    ]
    depends_on:
      - parse-server

volumes:
  mongo-data:
  config-vol:
